services:

    vidadeavion-outreach-web:

        container_name: vidadeavion-outreach-web

        image: vidadeavion/outreach

        build: 

            context: .

            dockerfile: Dockerfile

        ports:

            - 8000:80
